Coordinates = [
  [0, 0],
  [0.5, 0.866025403784],
  [1, 1.73205080757],
  [1.5, 2.59807621135],
  [2, 3.46410161514],
  [2.5, 4.33012701892],
  [1, 0],
  [1.5, 0.866025403784],
  [2, 1.73205080757],
  [2.5, 2.59807621135],
  [3, 3.46410161514],
  [3.5, 4.33012701892],
  [2, 0],
  [2.5, 0.866025403784],
  [3, 1.73205080757],
  [3.5, 2.59807621135],
  [4, 3.46410161514],
  [4.5, 4.33012701892],
  [3, 0],
  [3.5, 0.866025403784],
  [4, 1.73205080757],
  [4.5, 2.59807621135],
  [5, 3.46410161514],
  [5.5, 4.33012701892],
  [4, 0],
  [4.5, 0.866025403784],
  [5, 1.73205080757],
  [5.5, 2.59807621135],
  [6, 3.46410161514],
  [6.5, 4.33012701892],
  [5, 0],
  [5.5, 0.866025403784],
  [6, 1.73205080757],
  [6.5, 2.59807621135],
  [7, 3.46410161514],
  [7.5, 4.33012701892],
  [6, 0],
  [6.5, 0.866025403784],
  [7, 1.73205080757],
  [7.5, 2.59807621135],
  [8, 3.46410161514],
  [8.5, 4.33012701892],
  [7, 0],
  [7.5, 0.866025403784],
  [8, 1.73205080757],
  [8.5, 2.59807621135],
  [9, 3.46410161514],
  [9.5, 4.33012701892],
  [8, 0],
  [8.5, 0.866025403784],
  [9, 1.73205080757],
  [9.5, 2.59807621135],
  [10, 3.46410161514],
  [10.5, 4.33012701892],
  [9, 0],
  [9.5, 0.866025403784],
  [10, 1.73205080757],
  [10.5, 2.59807621135],
  [11, 3.46410161514],
  [11.5, 4.33012701892],
  [10, 0],
  [10.5, 0.866025403784],
  [11, 1.73205080757],
  [11.5, 2.59807621135],
  [12, 3.46410161514],
  [12.5, 4.33012701892],
  [11, 0],
  [11.5, 0.866025403784],
  [12, 1.73205080757],
  [12.5, 2.59807621135],
  [13, 3.46410161514],
  [13.5, 4.33012701892],
  [12, 0],
  [12.5, 0.866025403784],
  [13, 1.73205080757],
  [13.5, 2.59807621135],
  [14, 3.46410161514],
  [14.5, 4.33012701892],
  [13, 0],
  [13.5, 0.866025403784],
  [14, 1.73205080757],
  [14.5, 2.59807621135],
  [15, 3.46410161514],
  [15.5, 4.33012701892],
  [14, 0],
  [14.5, 0.866025403784],
  [15, 1.73205080757],
  [15.5, 2.59807621135],
  [16, 3.46410161514],
  [16.5, 4.33012701892],
  [15, 0],
  [15.5, 0.866025403784],
  [16, 1.73205080757],
  [16.5, 2.59807621135],
  [17, 3.46410161514],
  [17.5, 4.33012701892],
]

Interactions = [
  ['T', 'HUBBARDHOP', 0, 1],
  ['T', 'HUBBARDHOP', 0, 5],
  ['T', 'HUBBARDHOP', 0, 6],
  ['T', 'HUBBARDHOP', 1, 2],
  ['T', 'HUBBARDHOP', 1, 7],
  ['T', 'HUBBARDHOP', 2, 3],
  ['T', 'HUBBARDHOP', 2, 8],
  ['T', 'HUBBARDHOP', 3, 4],
  ['T', 'HUBBARDHOP', 3, 9],
  ['T', 'HUBBARDHOP', 4, 5],
  ['T', 'HUBBARDHOP', 4, 10],
  ['T', 'HUBBARDHOP', 5, 11],
  ['T', 'HUBBARDHOP', 6, 7],
  ['T', 'HUBBARDHOP', 6, 11],
  ['T', 'HUBBARDHOP', 6, 12],
  ['T', 'HUBBARDHOP', 7, 8],
  ['T', 'HUBBARDHOP', 7, 13],
  ['T', 'HUBBARDHOP', 8, 9],
  ['T', 'HUBBARDHOP', 8, 14],
  ['T', 'HUBBARDHOP', 9, 10],
  ['T', 'HUBBARDHOP', 9, 15],
  ['T', 'HUBBARDHOP', 10, 11],
  ['T', 'HUBBARDHOP', 10, 16],
  ['T', 'HUBBARDHOP', 11, 17],
  ['T', 'HUBBARDHOP', 12, 13],
  ['T', 'HUBBARDHOP', 12, 17],
  ['T', 'HUBBARDHOP', 12, 18],
  ['T', 'HUBBARDHOP', 13, 14],
  ['T', 'HUBBARDHOP', 13, 19],
  ['T', 'HUBBARDHOP', 14, 15],
  ['T', 'HUBBARDHOP', 14, 20],
  ['T', 'HUBBARDHOP', 15, 16],
  ['T', 'HUBBARDHOP', 15, 21],
  ['T', 'HUBBARDHOP', 16, 17],
  ['T', 'HUBBARDHOP', 16, 22],
  ['T', 'HUBBARDHOP', 17, 23],
  ['T', 'HUBBARDHOP', 18, 19],
  ['T', 'HUBBARDHOP', 18, 23],
  ['T', 'HUBBARDHOP', 18, 24],
  ['T', 'HUBBARDHOP', 19, 20],
  ['T', 'HUBBARDHOP', 19, 25],
  ['T', 'HUBBARDHOP', 20, 21],
  ['T', 'HUBBARDHOP', 20, 26],
  ['T', 'HUBBARDHOP', 21, 22],
  ['T', 'HUBBARDHOP', 21, 27],
  ['T', 'HUBBARDHOP', 22, 23],
  ['T', 'HUBBARDHOP', 22, 28],
  ['T', 'HUBBARDHOP', 23, 29],
  ['T', 'HUBBARDHOP', 24, 25],
  ['T', 'HUBBARDHOP', 24, 29],
  ['T', 'HUBBARDHOP', 24, 30],
  ['T', 'HUBBARDHOP', 25, 26],
  ['T', 'HUBBARDHOP', 25, 31],
  ['T', 'HUBBARDHOP', 26, 27],
  ['T', 'HUBBARDHOP', 26, 32],
  ['T', 'HUBBARDHOP', 27, 28],
  ['T', 'HUBBARDHOP', 27, 33],
  ['T', 'HUBBARDHOP', 28, 29],
  ['T', 'HUBBARDHOP', 28, 34],
  ['T', 'HUBBARDHOP', 29, 35],
  ['T', 'HUBBARDHOP', 30, 31],
  ['T', 'HUBBARDHOP', 30, 35],
  ['T', 'HUBBARDHOP', 30, 36],
  ['T', 'HUBBARDHOP', 31, 32],
  ['T', 'HUBBARDHOP', 31, 37],
  ['T', 'HUBBARDHOP', 32, 33],
  ['T', 'HUBBARDHOP', 32, 38],
  ['T', 'HUBBARDHOP', 33, 34],
  ['T', 'HUBBARDHOP', 33, 39],
  ['T', 'HUBBARDHOP', 34, 35],
  ['T', 'HUBBARDHOP', 34, 40],
  ['T', 'HUBBARDHOP', 35, 41],
  ['T', 'HUBBARDHOP', 36, 37],
  ['T', 'HUBBARDHOP', 36, 41],
  ['T', 'HUBBARDHOP', 36, 42],
  ['T', 'HUBBARDHOP', 37, 38],
  ['T', 'HUBBARDHOP', 37, 43],
  ['T', 'HUBBARDHOP', 38, 39],
  ['T', 'HUBBARDHOP', 38, 44],
  ['T', 'HUBBARDHOP', 39, 40],
  ['T', 'HUBBARDHOP', 39, 45],
  ['T', 'HUBBARDHOP', 40, 41],
  ['T', 'HUBBARDHOP', 40, 46],
  ['T', 'HUBBARDHOP', 41, 47],
  ['T', 'HUBBARDHOP', 42, 43],
  ['T', 'HUBBARDHOP', 42, 47],
  ['T', 'HUBBARDHOP', 42, 48],
  ['T', 'HUBBARDHOP', 43, 44],
  ['T', 'HUBBARDHOP', 43, 49],
  ['T', 'HUBBARDHOP', 44, 45],
  ['T', 'HUBBARDHOP', 44, 50],
  ['T', 'HUBBARDHOP', 45, 46],
  ['T', 'HUBBARDHOP', 45, 51],
  ['T', 'HUBBARDHOP', 46, 47],
  ['T', 'HUBBARDHOP', 46, 52],
  ['T', 'HUBBARDHOP', 47, 53],
  ['T', 'HUBBARDHOP', 48, 49],
  ['T', 'HUBBARDHOP', 48, 53],
  ['T', 'HUBBARDHOP', 48, 54],
  ['T', 'HUBBARDHOP', 49, 50],
  ['T', 'HUBBARDHOP', 49, 55],
  ['T', 'HUBBARDHOP', 50, 51],
  ['T', 'HUBBARDHOP', 50, 56],
  ['T', 'HUBBARDHOP', 51, 52],
  ['T', 'HUBBARDHOP', 51, 57],
  ['T', 'HUBBARDHOP', 52, 53],
  ['T', 'HUBBARDHOP', 52, 58],
  ['T', 'HUBBARDHOP', 53, 59],
  ['T', 'HUBBARDHOP', 54, 55],
  ['T', 'HUBBARDHOP', 54, 59],
  ['T', 'HUBBARDHOP', 54, 60],
  ['T', 'HUBBARDHOP', 55, 56],
  ['T', 'HUBBARDHOP', 55, 61],
  ['T', 'HUBBARDHOP', 56, 57],
  ['T', 'HUBBARDHOP', 56, 62],
  ['T', 'HUBBARDHOP', 57, 58],
  ['T', 'HUBBARDHOP', 57, 63],
  ['T', 'HUBBARDHOP', 58, 59],
  ['T', 'HUBBARDHOP', 58, 64],
  ['T', 'HUBBARDHOP', 59, 65],
  ['T', 'HUBBARDHOP', 60, 61],
  ['T', 'HUBBARDHOP', 60, 65],
  ['T', 'HUBBARDHOP', 60, 66],
  ['T', 'HUBBARDHOP', 61, 62],
  ['T', 'HUBBARDHOP', 61, 67],
  ['T', 'HUBBARDHOP', 62, 63],
  ['T', 'HUBBARDHOP', 62, 68],
  ['T', 'HUBBARDHOP', 63, 64],
  ['T', 'HUBBARDHOP', 63, 69],
  ['T', 'HUBBARDHOP', 64, 65],
  ['T', 'HUBBARDHOP', 64, 70],
  ['T', 'HUBBARDHOP', 65, 71],
  ['T', 'HUBBARDHOP', 66, 67],
  ['T', 'HUBBARDHOP', 66, 71],
  ['T', 'HUBBARDHOP', 66, 72],
  ['T', 'HUBBARDHOP', 67, 68],
  ['T', 'HUBBARDHOP', 67, 73],
  ['T', 'HUBBARDHOP', 68, 69],
  ['T', 'HUBBARDHOP', 68, 74],
  ['T', 'HUBBARDHOP', 69, 70],
  ['T', 'HUBBARDHOP', 69, 75],
  ['T', 'HUBBARDHOP', 70, 71],
  ['T', 'HUBBARDHOP', 70, 76],
  ['T', 'HUBBARDHOP', 71, 77],
  ['T', 'HUBBARDHOP', 72, 73],
  ['T', 'HUBBARDHOP', 72, 77],
  ['T', 'HUBBARDHOP', 72, 78],
  ['T', 'HUBBARDHOP', 73, 74],
  ['T', 'HUBBARDHOP', 73, 79],
  ['T', 'HUBBARDHOP', 74, 75],
  ['T', 'HUBBARDHOP', 74, 80],
  ['T', 'HUBBARDHOP', 75, 76],
  ['T', 'HUBBARDHOP', 75, 81],
  ['T', 'HUBBARDHOP', 76, 77],
  ['T', 'HUBBARDHOP', 76, 82],
  ['T', 'HUBBARDHOP', 77, 83],
  ['T', 'HUBBARDHOP', 78, 79],
  ['T', 'HUBBARDHOP', 78, 83],
  ['T', 'HUBBARDHOP', 78, 84],
  ['T', 'HUBBARDHOP', 79, 80],
  ['T', 'HUBBARDHOP', 79, 85],
  ['T', 'HUBBARDHOP', 80, 81],
  ['T', 'HUBBARDHOP', 80, 86],
  ['T', 'HUBBARDHOP', 81, 82],
  ['T', 'HUBBARDHOP', 81, 87],
  ['T', 'HUBBARDHOP', 82, 83],
  ['T', 'HUBBARDHOP', 82, 88],
  ['T', 'HUBBARDHOP', 83, 89],
  ['T', 'HUBBARDHOP', 84, 85],
  ['T', 'HUBBARDHOP', 84, 89],
  ['T', 'HUBBARDHOP', 84, 90],
  ['T', 'HUBBARDHOP', 85, 86],
  ['T', 'HUBBARDHOP', 85, 91],
  ['T', 'HUBBARDHOP', 86, 87],
  ['T', 'HUBBARDHOP', 86, 92],
  ['T', 'HUBBARDHOP', 87, 88],
  ['T', 'HUBBARDHOP', 87, 93],
  ['T', 'HUBBARDHOP', 88, 89],
  ['T', 'HUBBARDHOP', 88, 94],
  ['T', 'HUBBARDHOP', 89, 95],
  ['T', 'HUBBARDHOP', 90, 91],
  ['T', 'HUBBARDHOP', 90, 95],
  ['T', 'HUBBARDHOP', 91, 92],
  ['T', 'HUBBARDHOP', 92, 93],
  ['T', 'HUBBARDHOP', 93, 94],
  ['T', 'HUBBARDHOP', 94, 95],
  ['Tp', 'HUBBARDHOP', 0, 11],
  ['Tp', 'HUBBARDHOP', 1, 6],
  ['Tp', 'HUBBARDHOP', 2, 7],
  ['Tp', 'HUBBARDHOP', 3, 8],
  ['Tp', 'HUBBARDHOP', 4, 9],
  ['Tp', 'HUBBARDHOP', 5, 10],
  ['Tp', 'HUBBARDHOP', 6, 17],
  ['Tp', 'HUBBARDHOP', 7, 12],
  ['Tp', 'HUBBARDHOP', 8, 13],
  ['Tp', 'HUBBARDHOP', 9, 14],
  ['Tp', 'HUBBARDHOP', 10, 15],
  ['Tp', 'HUBBARDHOP', 11, 16],
  ['Tp', 'HUBBARDHOP', 12, 23],
  ['Tp', 'HUBBARDHOP', 13, 18],
  ['Tp', 'HUBBARDHOP', 14, 19],
  ['Tp', 'HUBBARDHOP', 15, 20],
  ['Tp', 'HUBBARDHOP', 16, 21],
  ['Tp', 'HUBBARDHOP', 17, 22],
  ['Tp', 'HUBBARDHOP', 18, 29],
  ['Tp', 'HUBBARDHOP', 19, 24],
  ['Tp', 'HUBBARDHOP', 20, 25],
  ['Tp', 'HUBBARDHOP', 21, 26],
  ['Tp', 'HUBBARDHOP', 22, 27],
  ['Tp', 'HUBBARDHOP', 23, 28],
  ['Tp', 'HUBBARDHOP', 24, 35],
  ['Tp', 'HUBBARDHOP', 25, 30],
  ['Tp', 'HUBBARDHOP', 26, 31],
  ['Tp', 'HUBBARDHOP', 27, 32],
  ['Tp', 'HUBBARDHOP', 28, 33],
  ['Tp', 'HUBBARDHOP', 29, 34],
  ['Tp', 'HUBBARDHOP', 30, 41],
  ['Tp', 'HUBBARDHOP', 31, 36],
  ['Tp', 'HUBBARDHOP', 32, 37],
  ['Tp', 'HUBBARDHOP', 33, 38],
  ['Tp', 'HUBBARDHOP', 34, 39],
  ['Tp', 'HUBBARDHOP', 35, 40],
  ['Tp', 'HUBBARDHOP', 36, 47],
  ['Tp', 'HUBBARDHOP', 37, 42],
  ['Tp', 'HUBBARDHOP', 38, 43],
  ['Tp', 'HUBBARDHOP', 39, 44],
  ['Tp', 'HUBBARDHOP', 40, 45],
  ['Tp', 'HUBBARDHOP', 41, 46],
  ['Tp', 'HUBBARDHOP', 42, 53],
  ['Tp', 'HUBBARDHOP', 43, 48],
  ['Tp', 'HUBBARDHOP', 44, 49],
  ['Tp', 'HUBBARDHOP', 45, 50],
  ['Tp', 'HUBBARDHOP', 46, 51],
  ['Tp', 'HUBBARDHOP', 47, 52],
  ['Tp', 'HUBBARDHOP', 48, 59],
  ['Tp', 'HUBBARDHOP', 49, 54],
  ['Tp', 'HUBBARDHOP', 50, 55],
  ['Tp', 'HUBBARDHOP', 51, 56],
  ['Tp', 'HUBBARDHOP', 52, 57],
  ['Tp', 'HUBBARDHOP', 53, 58],
  ['Tp', 'HUBBARDHOP', 54, 65],
  ['Tp', 'HUBBARDHOP', 55, 60],
  ['Tp', 'HUBBARDHOP', 56, 61],
  ['Tp', 'HUBBARDHOP', 57, 62],
  ['Tp', 'HUBBARDHOP', 58, 63],
  ['Tp', 'HUBBARDHOP', 59, 64],
  ['Tp', 'HUBBARDHOP', 60, 71],
  ['Tp', 'HUBBARDHOP', 61, 66],
  ['Tp', 'HUBBARDHOP', 62, 67],
  ['Tp', 'HUBBARDHOP', 63, 68],
  ['Tp', 'HUBBARDHOP', 64, 69],
  ['Tp', 'HUBBARDHOP', 65, 70],
  ['Tp', 'HUBBARDHOP', 66, 77],
  ['Tp', 'HUBBARDHOP', 67, 72],
  ['Tp', 'HUBBARDHOP', 68, 73],
  ['Tp', 'HUBBARDHOP', 69, 74],
  ['Tp', 'HUBBARDHOP', 70, 75],
  ['Tp', 'HUBBARDHOP', 71, 76],
  ['Tp', 'HUBBARDHOP', 72, 83],
  ['Tp', 'HUBBARDHOP', 73, 78],
  ['Tp', 'HUBBARDHOP', 74, 79],
  ['Tp', 'HUBBARDHOP', 75, 80],
  ['Tp', 'HUBBARDHOP', 76, 81],
  ['Tp', 'HUBBARDHOP', 77, 82],
  ['Tp', 'HUBBARDHOP', 78, 89],
  ['Tp', 'HUBBARDHOP', 79, 84],
  ['Tp', 'HUBBARDHOP', 80, 85],
  ['Tp', 'HUBBARDHOP', 81, 86],
  ['Tp', 'HUBBARDHOP', 82, 87],
  ['Tp', 'HUBBARDHOP', 83, 88],
  ['Tp', 'HUBBARDHOP', 84, 95],
  ['Tp', 'HUBBARDHOP', 85, 90],
  ['Tp', 'HUBBARDHOP', 86, 91],
  ['Tp', 'HUBBARDHOP', 87, 92],
  ['Tp', 'HUBBARDHOP', 88, 93],
  ['Tp', 'HUBBARDHOP', 89, 94],
]
