Coordinates = [
  [0, 0],
  [0.5, 0.866025403784],
  [1, 1.73205080757],
  [1, 0],
  [1.5, 0.866025403784],
  [2, 1.73205080757],
  [2, 0],
  [2.5, 0.866025403784],
  [3, 1.73205080757],
  [3, 0],
  [3.5, 0.866025403784],
  [4, 1.73205080757],
  [4, 0],
  [4.5, 0.866025403784],
  [5, 1.73205080757],
  [5, 0],
  [5.5, 0.866025403784],
  [6, 1.73205080757],
  [6, 0],
  [6.5, 0.866025403784],
  [7, 1.73205080757],
  [7, 0],
  [7.5, 0.866025403784],
  [8, 1.73205080757],
  [8, 0],
  [8.5, 0.866025403784],
  [9, 1.73205080757],
  [9, 0],
  [9.5, 0.866025403784],
  [10, 1.73205080757],
  [10, 0],
  [10.5, 0.866025403784],
  [11, 1.73205080757],
  [11, 0],
  [11.5, 0.866025403784],
  [12, 1.73205080757],
  [12, 0],
  [12.5, 0.866025403784],
  [13, 1.73205080757],
  [13, 0],
  [13.5, 0.866025403784],
  [14, 1.73205080757],
  [14, 0],
  [14.5, 0.866025403784],
  [15, 1.73205080757],
  [15, 0],
  [15.5, 0.866025403784],
  [16, 1.73205080757],
  [16, 0],
  [16.5, 0.866025403784],
  [17, 1.73205080757],
  [17, 0],
  [17.5, 0.866025403784],
  [18, 1.73205080757],
  [18, 0],
  [18.5, 0.866025403784],
  [19, 1.73205080757],
  [19, 0],
  [19.5, 0.866025403784],
  [20, 1.73205080757],
  [20, 0],
  [20.5, 0.866025403784],
  [21, 1.73205080757],
  [21, 0],
  [21.5, 0.866025403784],
  [22, 1.73205080757],
  [22, 0],
  [22.5, 0.866025403784],
  [23, 1.73205080757],
  [23, 0],
  [23.5, 0.866025403784],
  [24, 1.73205080757],
  [24, 0],
  [24.5, 0.866025403784],
  [25, 1.73205080757],
  [25, 0],
  [25.5, 0.866025403784],
  [26, 1.73205080757],
  [26, 0],
  [26.5, 0.866025403784],
  [27, 1.73205080757],
  [27, 0],
  [27.5, 0.866025403784],
  [28, 1.73205080757],
  [28, 0],
  [28.5, 0.866025403784],
  [29, 1.73205080757],
  [29, 0],
  [29.5, 0.866025403784],
  [30, 1.73205080757],
  [30, 0],
  [30.5, 0.866025403784],
  [31, 1.73205080757],
  [31, 0],
  [31.5, 0.866025403784],
  [32, 1.73205080757],
]

Interactions = [
  ['T', 'HUBBARDHOP', 0, 1],
  ['T', 'HUBBARDHOP', 0, 2],
  ['T', 'HUBBARDHOP', 0, 3],
  ['T', 'HUBBARDHOP', 1, 2],
  ['T', 'HUBBARDHOP', 1, 4],
  ['T', 'HUBBARDHOP', 2, 5],
  ['T', 'HUBBARDHOP', 3, 4],
  ['T', 'HUBBARDHOP', 3, 5],
  ['T', 'HUBBARDHOP', 3, 6],
  ['T', 'HUBBARDHOP', 4, 5],
  ['T', 'HUBBARDHOP', 4, 7],
  ['T', 'HUBBARDHOP', 5, 8],
  ['T', 'HUBBARDHOP', 6, 7],
  ['T', 'HUBBARDHOP', 6, 8],
  ['T', 'HUBBARDHOP', 6, 9],
  ['T', 'HUBBARDHOP', 7, 8],
  ['T', 'HUBBARDHOP', 7, 10],
  ['T', 'HUBBARDHOP', 8, 11],
  ['T', 'HUBBARDHOP', 9, 10],
  ['T', 'HUBBARDHOP', 9, 11],
  ['T', 'HUBBARDHOP', 9, 12],
  ['T', 'HUBBARDHOP', 10, 11],
  ['T', 'HUBBARDHOP', 10, 13],
  ['T', 'HUBBARDHOP', 11, 14],
  ['T', 'HUBBARDHOP', 12, 13],
  ['T', 'HUBBARDHOP', 12, 14],
  ['T', 'HUBBARDHOP', 12, 15],
  ['T', 'HUBBARDHOP', 13, 14],
  ['T', 'HUBBARDHOP', 13, 16],
  ['T', 'HUBBARDHOP', 14, 17],
  ['T', 'HUBBARDHOP', 15, 16],
  ['T', 'HUBBARDHOP', 15, 17],
  ['T', 'HUBBARDHOP', 15, 18],
  ['T', 'HUBBARDHOP', 16, 17],
  ['T', 'HUBBARDHOP', 16, 19],
  ['T', 'HUBBARDHOP', 17, 20],
  ['T', 'HUBBARDHOP', 18, 19],
  ['T', 'HUBBARDHOP', 18, 20],
  ['T', 'HUBBARDHOP', 18, 21],
  ['T', 'HUBBARDHOP', 19, 20],
  ['T', 'HUBBARDHOP', 19, 22],
  ['T', 'HUBBARDHOP', 20, 23],
  ['T', 'HUBBARDHOP', 21, 22],
  ['T', 'HUBBARDHOP', 21, 23],
  ['T', 'HUBBARDHOP', 21, 24],
  ['T', 'HUBBARDHOP', 22, 23],
  ['T', 'HUBBARDHOP', 22, 25],
  ['T', 'HUBBARDHOP', 23, 26],
  ['T', 'HUBBARDHOP', 24, 25],
  ['T', 'HUBBARDHOP', 24, 26],
  ['T', 'HUBBARDHOP', 24, 27],
  ['T', 'HUBBARDHOP', 25, 26],
  ['T', 'HUBBARDHOP', 25, 28],
  ['T', 'HUBBARDHOP', 26, 29],
  ['T', 'HUBBARDHOP', 27, 28],
  ['T', 'HUBBARDHOP', 27, 29],
  ['T', 'HUBBARDHOP', 27, 30],
  ['T', 'HUBBARDHOP', 28, 29],
  ['T', 'HUBBARDHOP', 28, 31],
  ['T', 'HUBBARDHOP', 29, 32],
  ['T', 'HUBBARDHOP', 30, 31],
  ['T', 'HUBBARDHOP', 30, 32],
  ['T', 'HUBBARDHOP', 30, 33],
  ['T', 'HUBBARDHOP', 31, 32],
  ['T', 'HUBBARDHOP', 31, 34],
  ['T', 'HUBBARDHOP', 32, 35],
  ['T', 'HUBBARDHOP', 33, 34],
  ['T', 'HUBBARDHOP', 33, 35],
  ['T', 'HUBBARDHOP', 33, 36],
  ['T', 'HUBBARDHOP', 34, 35],
  ['T', 'HUBBARDHOP', 34, 37],
  ['T', 'HUBBARDHOP', 35, 38],
  ['T', 'HUBBARDHOP', 36, 37],
  ['T', 'HUBBARDHOP', 36, 38],
  ['T', 'HUBBARDHOP', 36, 39],
  ['T', 'HUBBARDHOP', 37, 38],
  ['T', 'HUBBARDHOP', 37, 40],
  ['T', 'HUBBARDHOP', 38, 41],
  ['T', 'HUBBARDHOP', 39, 40],
  ['T', 'HUBBARDHOP', 39, 41],
  ['T', 'HUBBARDHOP', 39, 42],
  ['T', 'HUBBARDHOP', 40, 41],
  ['T', 'HUBBARDHOP', 40, 43],
  ['T', 'HUBBARDHOP', 41, 44],
  ['T', 'HUBBARDHOP', 42, 43],
  ['T', 'HUBBARDHOP', 42, 44],
  ['T', 'HUBBARDHOP', 42, 45],
  ['T', 'HUBBARDHOP', 43, 44],
  ['T', 'HUBBARDHOP', 43, 46],
  ['T', 'HUBBARDHOP', 44, 47],
  ['T', 'HUBBARDHOP', 45, 46],
  ['T', 'HUBBARDHOP', 45, 47],
  ['T', 'HUBBARDHOP', 45, 48],
  ['T', 'HUBBARDHOP', 46, 47],
  ['T', 'HUBBARDHOP', 46, 49],
  ['T', 'HUBBARDHOP', 47, 50],
  ['T', 'HUBBARDHOP', 48, 49],
  ['T', 'HUBBARDHOP', 48, 50],
  ['T', 'HUBBARDHOP', 48, 51],
  ['T', 'HUBBARDHOP', 49, 50],
  ['T', 'HUBBARDHOP', 49, 52],
  ['T', 'HUBBARDHOP', 50, 53],
  ['T', 'HUBBARDHOP', 51, 52],
  ['T', 'HUBBARDHOP', 51, 53],
  ['T', 'HUBBARDHOP', 51, 54],
  ['T', 'HUBBARDHOP', 52, 53],
  ['T', 'HUBBARDHOP', 52, 55],
  ['T', 'HUBBARDHOP', 53, 56],
  ['T', 'HUBBARDHOP', 54, 55],
  ['T', 'HUBBARDHOP', 54, 56],
  ['T', 'HUBBARDHOP', 54, 57],
  ['T', 'HUBBARDHOP', 55, 56],
  ['T', 'HUBBARDHOP', 55, 58],
  ['T', 'HUBBARDHOP', 56, 59],
  ['T', 'HUBBARDHOP', 57, 58],
  ['T', 'HUBBARDHOP', 57, 59],
  ['T', 'HUBBARDHOP', 57, 60],
  ['T', 'HUBBARDHOP', 58, 59],
  ['T', 'HUBBARDHOP', 58, 61],
  ['T', 'HUBBARDHOP', 59, 62],
  ['T', 'HUBBARDHOP', 60, 61],
  ['T', 'HUBBARDHOP', 60, 62],
  ['T', 'HUBBARDHOP', 60, 63],
  ['T', 'HUBBARDHOP', 61, 62],
  ['T', 'HUBBARDHOP', 61, 64],
  ['T', 'HUBBARDHOP', 62, 65],
  ['T', 'HUBBARDHOP', 63, 64],
  ['T', 'HUBBARDHOP', 63, 65],
  ['T', 'HUBBARDHOP', 63, 66],
  ['T', 'HUBBARDHOP', 64, 65],
  ['T', 'HUBBARDHOP', 64, 67],
  ['T', 'HUBBARDHOP', 65, 68],
  ['T', 'HUBBARDHOP', 66, 67],
  ['T', 'HUBBARDHOP', 66, 68],
  ['T', 'HUBBARDHOP', 66, 69],
  ['T', 'HUBBARDHOP', 67, 68],
  ['T', 'HUBBARDHOP', 67, 70],
  ['T', 'HUBBARDHOP', 68, 71],
  ['T', 'HUBBARDHOP', 69, 70],
  ['T', 'HUBBARDHOP', 69, 71],
  ['T', 'HUBBARDHOP', 69, 72],
  ['T', 'HUBBARDHOP', 70, 71],
  ['T', 'HUBBARDHOP', 70, 73],
  ['T', 'HUBBARDHOP', 71, 74],
  ['T', 'HUBBARDHOP', 72, 73],
  ['T', 'HUBBARDHOP', 72, 74],
  ['T', 'HUBBARDHOP', 72, 75],
  ['T', 'HUBBARDHOP', 73, 74],
  ['T', 'HUBBARDHOP', 73, 76],
  ['T', 'HUBBARDHOP', 74, 77],
  ['T', 'HUBBARDHOP', 75, 76],
  ['T', 'HUBBARDHOP', 75, 77],
  ['T', 'HUBBARDHOP', 75, 78],
  ['T', 'HUBBARDHOP', 76, 77],
  ['T', 'HUBBARDHOP', 76, 79],
  ['T', 'HUBBARDHOP', 77, 80],
  ['T', 'HUBBARDHOP', 78, 79],
  ['T', 'HUBBARDHOP', 78, 80],
  ['T', 'HUBBARDHOP', 78, 81],
  ['T', 'HUBBARDHOP', 79, 80],
  ['T', 'HUBBARDHOP', 79, 82],
  ['T', 'HUBBARDHOP', 80, 83],
  ['T', 'HUBBARDHOP', 81, 82],
  ['T', 'HUBBARDHOP', 81, 83],
  ['T', 'HUBBARDHOP', 81, 84],
  ['T', 'HUBBARDHOP', 82, 83],
  ['T', 'HUBBARDHOP', 82, 85],
  ['T', 'HUBBARDHOP', 83, 86],
  ['T', 'HUBBARDHOP', 84, 85],
  ['T', 'HUBBARDHOP', 84, 86],
  ['T', 'HUBBARDHOP', 84, 87],
  ['T', 'HUBBARDHOP', 85, 86],
  ['T', 'HUBBARDHOP', 85, 88],
  ['T', 'HUBBARDHOP', 86, 89],
  ['T', 'HUBBARDHOP', 87, 88],
  ['T', 'HUBBARDHOP', 87, 89],
  ['T', 'HUBBARDHOP', 87, 90],
  ['T', 'HUBBARDHOP', 88, 89],
  ['T', 'HUBBARDHOP', 88, 91],
  ['T', 'HUBBARDHOP', 89, 92],
  ['T', 'HUBBARDHOP', 90, 91],
  ['T', 'HUBBARDHOP', 90, 92],
  ['T', 'HUBBARDHOP', 90, 93],
  ['T', 'HUBBARDHOP', 91, 92],
  ['T', 'HUBBARDHOP', 91, 94],
  ['T', 'HUBBARDHOP', 92, 95],
  ['T', 'HUBBARDHOP', 93, 94],
  ['T', 'HUBBARDHOP', 93, 95],
  ['T', 'HUBBARDHOP', 94, 95],
  ['Tp', 'HUBBARDHOP', 0, 5],
  ['Tp', 'HUBBARDHOP', 1, 3],
  ['Tp', 'HUBBARDHOP', 2, 4],
  ['Tp', 'HUBBARDHOP', 3, 8],
  ['Tp', 'HUBBARDHOP', 4, 6],
  ['Tp', 'HUBBARDHOP', 5, 7],
  ['Tp', 'HUBBARDHOP', 6, 11],
  ['Tp', 'HUBBARDHOP', 7, 9],
  ['Tp', 'HUBBARDHOP', 8, 10],
  ['Tp', 'HUBBARDHOP', 9, 14],
  ['Tp', 'HUBBARDHOP', 10, 12],
  ['Tp', 'HUBBARDHOP', 11, 13],
  ['Tp', 'HUBBARDHOP', 12, 17],
  ['Tp', 'HUBBARDHOP', 13, 15],
  ['Tp', 'HUBBARDHOP', 14, 16],
  ['Tp', 'HUBBARDHOP', 15, 20],
  ['Tp', 'HUBBARDHOP', 16, 18],
  ['Tp', 'HUBBARDHOP', 17, 19],
  ['Tp', 'HUBBARDHOP', 18, 23],
  ['Tp', 'HUBBARDHOP', 19, 21],
  ['Tp', 'HUBBARDHOP', 20, 22],
  ['Tp', 'HUBBARDHOP', 21, 26],
  ['Tp', 'HUBBARDHOP', 22, 24],
  ['Tp', 'HUBBARDHOP', 23, 25],
  ['Tp', 'HUBBARDHOP', 24, 29],
  ['Tp', 'HUBBARDHOP', 25, 27],
  ['Tp', 'HUBBARDHOP', 26, 28],
  ['Tp', 'HUBBARDHOP', 27, 32],
  ['Tp', 'HUBBARDHOP', 28, 30],
  ['Tp', 'HUBBARDHOP', 29, 31],
  ['Tp', 'HUBBARDHOP', 30, 35],
  ['Tp', 'HUBBARDHOP', 31, 33],
  ['Tp', 'HUBBARDHOP', 32, 34],
  ['Tp', 'HUBBARDHOP', 33, 38],
  ['Tp', 'HUBBARDHOP', 34, 36],
  ['Tp', 'HUBBARDHOP', 35, 37],
  ['Tp', 'HUBBARDHOP', 36, 41],
  ['Tp', 'HUBBARDHOP', 37, 39],
  ['Tp', 'HUBBARDHOP', 38, 40],
  ['Tp', 'HUBBARDHOP', 39, 44],
  ['Tp', 'HUBBARDHOP', 40, 42],
  ['Tp', 'HUBBARDHOP', 41, 43],
  ['Tp', 'HUBBARDHOP', 42, 47],
  ['Tp', 'HUBBARDHOP', 43, 45],
  ['Tp', 'HUBBARDHOP', 44, 46],
  ['Tp', 'HUBBARDHOP', 45, 50],
  ['Tp', 'HUBBARDHOP', 46, 48],
  ['Tp', 'HUBBARDHOP', 47, 49],
  ['Tp', 'HUBBARDHOP', 48, 53],
  ['Tp', 'HUBBARDHOP', 49, 51],
  ['Tp', 'HUBBARDHOP', 50, 52],
  ['Tp', 'HUBBARDHOP', 51, 56],
  ['Tp', 'HUBBARDHOP', 52, 54],
  ['Tp', 'HUBBARDHOP', 53, 55],
  ['Tp', 'HUBBARDHOP', 54, 59],
  ['Tp', 'HUBBARDHOP', 55, 57],
  ['Tp', 'HUBBARDHOP', 56, 58],
  ['Tp', 'HUBBARDHOP', 57, 62],
  ['Tp', 'HUBBARDHOP', 58, 60],
  ['Tp', 'HUBBARDHOP', 59, 61],
  ['Tp', 'HUBBARDHOP', 60, 65],
  ['Tp', 'HUBBARDHOP', 61, 63],
  ['Tp', 'HUBBARDHOP', 62, 64],
  ['Tp', 'HUBBARDHOP', 63, 68],
  ['Tp', 'HUBBARDHOP', 64, 66],
  ['Tp', 'HUBBARDHOP', 65, 67],
  ['Tp', 'HUBBARDHOP', 66, 71],
  ['Tp', 'HUBBARDHOP', 67, 69],
  ['Tp', 'HUBBARDHOP', 68, 70],
  ['Tp', 'HUBBARDHOP', 69, 74],
  ['Tp', 'HUBBARDHOP', 70, 72],
  ['Tp', 'HUBBARDHOP', 71, 73],
  ['Tp', 'HUBBARDHOP', 72, 77],
  ['Tp', 'HUBBARDHOP', 73, 75],
  ['Tp', 'HUBBARDHOP', 74, 76],
  ['Tp', 'HUBBARDHOP', 75, 80],
  ['Tp', 'HUBBARDHOP', 76, 78],
  ['Tp', 'HUBBARDHOP', 77, 79],
  ['Tp', 'HUBBARDHOP', 78, 83],
  ['Tp', 'HUBBARDHOP', 79, 81],
  ['Tp', 'HUBBARDHOP', 80, 82],
  ['Tp', 'HUBBARDHOP', 81, 86],
  ['Tp', 'HUBBARDHOP', 82, 84],
  ['Tp', 'HUBBARDHOP', 83, 85],
  ['Tp', 'HUBBARDHOP', 84, 89],
  ['Tp', 'HUBBARDHOP', 85, 87],
  ['Tp', 'HUBBARDHOP', 86, 88],
  ['Tp', 'HUBBARDHOP', 87, 92],
  ['Tp', 'HUBBARDHOP', 88, 90],
  ['Tp', 'HUBBARDHOP', 89, 91],
  ['Tp', 'HUBBARDHOP', 90, 95],
  ['Tp', 'HUBBARDHOP', 91, 93],
  ['Tp', 'HUBBARDHOP', 92, 94],
]
