Coordinates = [
  [0, 0],
  [0.5, 0.866025403784],
  [1, 1.73205080757],
  [1, 0],
  [1.5, 0.866025403784],
  [2, 1.73205080757],
  [2, 0],
  [2.5, 0.866025403784],
  [3, 1.73205080757],
  [3, 0],
  [3.5, 0.866025403784],
  [4, 1.73205080757],
  [4, 0],
  [4.5, 0.866025403784],
  [5, 1.73205080757],
  [5, 0],
  [5.5, 0.866025403784],
  [6, 1.73205080757],
  [6, 0],
  [6.5, 0.866025403784],
  [7, 1.73205080757],
  [7, 0],
  [7.5, 0.866025403784],
  [8, 1.73205080757],
  [8, 0],
  [8.5, 0.866025403784],
  [9, 1.73205080757],
  [9, 0],
  [9.5, 0.866025403784],
  [10, 1.73205080757],
  [10, 0],
  [10.5, 0.866025403784],
  [11, 1.73205080757],
  [11, 0],
  [11.5, 0.866025403784],
  [12, 1.73205080757],
  [12, 0],
  [12.5, 0.866025403784],
  [13, 1.73205080757],
  [13, 0],
  [13.5, 0.866025403784],
  [14, 1.73205080757],
  [14, 0],
  [14.5, 0.866025403784],
  [15, 1.73205080757],
  [15, 0],
  [15.5, 0.866025403784],
  [16, 1.73205080757],
]

Interactions = [
  ['T', 'HUBBARDHOP', 0, 1],
  ['T', 'HUBBARDHOP', 0, 2],
  ['T', 'HUBBARDHOP', 0, 3],
  ['T', 'HUBBARDHOP', 1, 2],
  ['T', 'HUBBARDHOP', 1, 4],
  ['T', 'HUBBARDHOP', 2, 5],
  ['T', 'HUBBARDHOP', 3, 4],
  ['T', 'HUBBARDHOP', 3, 5],
  ['T', 'HUBBARDHOP', 3, 6],
  ['T', 'HUBBARDHOP', 4, 5],
  ['T', 'HUBBARDHOP', 4, 7],
  ['T', 'HUBBARDHOP', 5, 8],
  ['T', 'HUBBARDHOP', 6, 7],
  ['T', 'HUBBARDHOP', 6, 8],
  ['T', 'HUBBARDHOP', 6, 9],
  ['T', 'HUBBARDHOP', 7, 8],
  ['T', 'HUBBARDHOP', 7, 10],
  ['T', 'HUBBARDHOP', 8, 11],
  ['T', 'HUBBARDHOP', 9, 10],
  ['T', 'HUBBARDHOP', 9, 11],
  ['T', 'HUBBARDHOP', 9, 12],
  ['T', 'HUBBARDHOP', 10, 11],
  ['T', 'HUBBARDHOP', 10, 13],
  ['T', 'HUBBARDHOP', 11, 14],
  ['T', 'HUBBARDHOP', 12, 13],
  ['T', 'HUBBARDHOP', 12, 14],
  ['T', 'HUBBARDHOP', 12, 15],
  ['T', 'HUBBARDHOP', 13, 14],
  ['T', 'HUBBARDHOP', 13, 16],
  ['T', 'HUBBARDHOP', 14, 17],
  ['T', 'HUBBARDHOP', 15, 16],
  ['T', 'HUBBARDHOP', 15, 17],
  ['T', 'HUBBARDHOP', 15, 18],
  ['T', 'HUBBARDHOP', 16, 17],
  ['T', 'HUBBARDHOP', 16, 19],
  ['T', 'HUBBARDHOP', 17, 20],
  ['T', 'HUBBARDHOP', 18, 19],
  ['T', 'HUBBARDHOP', 18, 20],
  ['T', 'HUBBARDHOP', 18, 21],
  ['T', 'HUBBARDHOP', 19, 20],
  ['T', 'HUBBARDHOP', 19, 22],
  ['T', 'HUBBARDHOP', 20, 23],
  ['T', 'HUBBARDHOP', 21, 22],
  ['T', 'HUBBARDHOP', 21, 23],
  ['T', 'HUBBARDHOP', 21, 24],
  ['T', 'HUBBARDHOP', 22, 23],
  ['T', 'HUBBARDHOP', 22, 25],
  ['T', 'HUBBARDHOP', 23, 26],
  ['T', 'HUBBARDHOP', 24, 25],
  ['T', 'HUBBARDHOP', 24, 26],
  ['T', 'HUBBARDHOP', 24, 27],
  ['T', 'HUBBARDHOP', 25, 26],
  ['T', 'HUBBARDHOP', 25, 28],
  ['T', 'HUBBARDHOP', 26, 29],
  ['T', 'HUBBARDHOP', 27, 28],
  ['T', 'HUBBARDHOP', 27, 29],
  ['T', 'HUBBARDHOP', 27, 30],
  ['T', 'HUBBARDHOP', 28, 29],
  ['T', 'HUBBARDHOP', 28, 31],
  ['T', 'HUBBARDHOP', 29, 32],
  ['T', 'HUBBARDHOP', 30, 31],
  ['T', 'HUBBARDHOP', 30, 32],
  ['T', 'HUBBARDHOP', 30, 33],
  ['T', 'HUBBARDHOP', 31, 32],
  ['T', 'HUBBARDHOP', 31, 34],
  ['T', 'HUBBARDHOP', 32, 35],
  ['T', 'HUBBARDHOP', 33, 34],
  ['T', 'HUBBARDHOP', 33, 35],
  ['T', 'HUBBARDHOP', 33, 36],
  ['T', 'HUBBARDHOP', 34, 35],
  ['T', 'HUBBARDHOP', 34, 37],
  ['T', 'HUBBARDHOP', 35, 38],
  ['T', 'HUBBARDHOP', 36, 37],
  ['T', 'HUBBARDHOP', 36, 38],
  ['T', 'HUBBARDHOP', 36, 39],
  ['T', 'HUBBARDHOP', 37, 38],
  ['T', 'HUBBARDHOP', 37, 40],
  ['T', 'HUBBARDHOP', 38, 41],
  ['T', 'HUBBARDHOP', 39, 40],
  ['T', 'HUBBARDHOP', 39, 41],
  ['T', 'HUBBARDHOP', 39, 42],
  ['T', 'HUBBARDHOP', 40, 41],
  ['T', 'HUBBARDHOP', 40, 43],
  ['T', 'HUBBARDHOP', 41, 44],
  ['T', 'HUBBARDHOP', 42, 43],
  ['T', 'HUBBARDHOP', 42, 44],
  ['T', 'HUBBARDHOP', 42, 45],
  ['T', 'HUBBARDHOP', 43, 44],
  ['T', 'HUBBARDHOP', 43, 46],
  ['T', 'HUBBARDHOP', 44, 47],
  ['T', 'HUBBARDHOP', 45, 46],
  ['T', 'HUBBARDHOP', 45, 47],
  ['T', 'HUBBARDHOP', 46, 47],
  ['Tp', 'HUBBARDHOP', 0, 5],
  ['Tp', 'HUBBARDHOP', 1, 3],
  ['Tp', 'HUBBARDHOP', 2, 4],
  ['Tp', 'HUBBARDHOP', 3, 8],
  ['Tp', 'HUBBARDHOP', 4, 6],
  ['Tp', 'HUBBARDHOP', 5, 7],
  ['Tp', 'HUBBARDHOP', 6, 11],
  ['Tp', 'HUBBARDHOP', 7, 9],
  ['Tp', 'HUBBARDHOP', 8, 10],
  ['Tp', 'HUBBARDHOP', 9, 14],
  ['Tp', 'HUBBARDHOP', 10, 12],
  ['Tp', 'HUBBARDHOP', 11, 13],
  ['Tp', 'HUBBARDHOP', 12, 17],
  ['Tp', 'HUBBARDHOP', 13, 15],
  ['Tp', 'HUBBARDHOP', 14, 16],
  ['Tp', 'HUBBARDHOP', 15, 20],
  ['Tp', 'HUBBARDHOP', 16, 18],
  ['Tp', 'HUBBARDHOP', 17, 19],
  ['Tp', 'HUBBARDHOP', 18, 23],
  ['Tp', 'HUBBARDHOP', 19, 21],
  ['Tp', 'HUBBARDHOP', 20, 22],
  ['Tp', 'HUBBARDHOP', 21, 26],
  ['Tp', 'HUBBARDHOP', 22, 24],
  ['Tp', 'HUBBARDHOP', 23, 25],
  ['Tp', 'HUBBARDHOP', 24, 29],
  ['Tp', 'HUBBARDHOP', 25, 27],
  ['Tp', 'HUBBARDHOP', 26, 28],
  ['Tp', 'HUBBARDHOP', 27, 32],
  ['Tp', 'HUBBARDHOP', 28, 30],
  ['Tp', 'HUBBARDHOP', 29, 31],
  ['Tp', 'HUBBARDHOP', 30, 35],
  ['Tp', 'HUBBARDHOP', 31, 33],
  ['Tp', 'HUBBARDHOP', 32, 34],
  ['Tp', 'HUBBARDHOP', 33, 38],
  ['Tp', 'HUBBARDHOP', 34, 36],
  ['Tp', 'HUBBARDHOP', 35, 37],
  ['Tp', 'HUBBARDHOP', 36, 41],
  ['Tp', 'HUBBARDHOP', 37, 39],
  ['Tp', 'HUBBARDHOP', 38, 40],
  ['Tp', 'HUBBARDHOP', 39, 44],
  ['Tp', 'HUBBARDHOP', 40, 42],
  ['Tp', 'HUBBARDHOP', 41, 43],
  ['Tp', 'HUBBARDHOP', 42, 47],
  ['Tp', 'HUBBARDHOP', 43, 45],
  ['Tp', 'HUBBARDHOP', 44, 46],
]
