Coordinates = [
  [0, 0],
  [0.5, 0.866025403784],
  [1, 1.73205080757],
  [1.5, 2.59807621135],
  [1, 0],
  [1.5, 0.866025403784],
  [2, 1.73205080757],
  [2.5, 2.59807621135],
  [2, 0],
  [2.5, 0.866025403784],
  [3, 1.73205080757],
  [3.5, 2.59807621135],
  [3, 0],
  [3.5, 0.866025403784],
  [4, 1.73205080757],
  [4.5, 2.59807621135],
  [4, 0],
  [4.5, 0.866025403784],
  [5, 1.73205080757],
  [5.5, 2.59807621135],
  [5, 0],
  [5.5, 0.866025403784],
  [6, 1.73205080757],
  [6.5, 2.59807621135],
  [6, 0],
  [6.5, 0.866025403784],
  [7, 1.73205080757],
  [7.5, 2.59807621135],
  [7, 0],
  [7.5, 0.866025403784],
  [8, 1.73205080757],
  [8.5, 2.59807621135],
  [8, 0],
  [8.5, 0.866025403784],
  [9, 1.73205080757],
  [9.5, 2.59807621135],
  [9, 0],
  [9.5, 0.866025403784],
  [10, 1.73205080757],
  [10.5, 2.59807621135],
  [10, 0],
  [10.5, 0.866025403784],
  [11, 1.73205080757],
  [11.5, 2.59807621135],
  [11, 0],
  [11.5, 0.866025403784],
  [12, 1.73205080757],
  [12.5, 2.59807621135],
  [12, 0],
  [12.5, 0.866025403784],
  [13, 1.73205080757],
  [13.5, 2.59807621135],
  [13, 0],
  [13.5, 0.866025403784],
  [14, 1.73205080757],
  [14.5, 2.59807621135],
  [14, 0],
  [14.5, 0.866025403784],
  [15, 1.73205080757],
  [15.5, 2.59807621135],
  [15, 0],
  [15.5, 0.866025403784],
  [16, 1.73205080757],
  [16.5, 2.59807621135],
  [16, 0],
  [16.5, 0.866025403784],
  [17, 1.73205080757],
  [17.5, 2.59807621135],
  [17, 0],
  [17.5, 0.866025403784],
  [18, 1.73205080757],
  [18.5, 2.59807621135],
  [18, 0],
  [18.5, 0.866025403784],
  [19, 1.73205080757],
  [19.5, 2.59807621135],
  [19, 0],
  [19.5, 0.866025403784],
  [20, 1.73205080757],
  [20.5, 2.59807621135],
  [20, 0],
  [20.5, 0.866025403784],
  [21, 1.73205080757],
  [21.5, 2.59807621135],
  [21, 0],
  [21.5, 0.866025403784],
  [22, 1.73205080757],
  [22.5, 2.59807621135],
  [22, 0],
  [22.5, 0.866025403784],
  [23, 1.73205080757],
  [23.5, 2.59807621135],
  [23, 0],
  [23.5, 0.866025403784],
  [24, 1.73205080757],
  [24.5, 2.59807621135],
  [24, 0],
  [24.5, 0.866025403784],
  [25, 1.73205080757],
  [25.5, 2.59807621135],
  [25, 0],
  [25.5, 0.866025403784],
  [26, 1.73205080757],
  [26.5, 2.59807621135],
  [26, 0],
  [26.5, 0.866025403784],
  [27, 1.73205080757],
  [27.5, 2.59807621135],
  [27, 0],
  [27.5, 0.866025403784],
  [28, 1.73205080757],
  [28.5, 2.59807621135],
  [28, 0],
  [28.5, 0.866025403784],
  [29, 1.73205080757],
  [29.5, 2.59807621135],
  [29, 0],
  [29.5, 0.866025403784],
  [30, 1.73205080757],
  [30.5, 2.59807621135],
  [30, 0],
  [30.5, 0.866025403784],
  [31, 1.73205080757],
  [31.5, 2.59807621135],
  [31, 0],
  [31.5, 0.866025403784],
  [32, 1.73205080757],
  [32.5, 2.59807621135],
]

Interactions = [
  ['T', 'HUBBARDHOP', 0, 1],
  ['T', 'HUBBARDHOP', 0, 3],
  ['T', 'HUBBARDHOP', 0, 4],
  ['T', 'HUBBARDHOP', 1, 2],
  ['T', 'HUBBARDHOP', 1, 5],
  ['T', 'HUBBARDHOP', 2, 3],
  ['T', 'HUBBARDHOP', 2, 6],
  ['T', 'HUBBARDHOP', 3, 7],
  ['T', 'HUBBARDHOP', 4, 5],
  ['T', 'HUBBARDHOP', 4, 7],
  ['T', 'HUBBARDHOP', 4, 8],
  ['T', 'HUBBARDHOP', 5, 6],
  ['T', 'HUBBARDHOP', 5, 9],
  ['T', 'HUBBARDHOP', 6, 7],
  ['T', 'HUBBARDHOP', 6, 10],
  ['T', 'HUBBARDHOP', 7, 11],
  ['T', 'HUBBARDHOP', 8, 9],
  ['T', 'HUBBARDHOP', 8, 11],
  ['T', 'HUBBARDHOP', 8, 12],
  ['T', 'HUBBARDHOP', 9, 10],
  ['T', 'HUBBARDHOP', 9, 13],
  ['T', 'HUBBARDHOP', 10, 11],
  ['T', 'HUBBARDHOP', 10, 14],
  ['T', 'HUBBARDHOP', 11, 15],
  ['T', 'HUBBARDHOP', 12, 13],
  ['T', 'HUBBARDHOP', 12, 15],
  ['T', 'HUBBARDHOP', 12, 16],
  ['T', 'HUBBARDHOP', 13, 14],
  ['T', 'HUBBARDHOP', 13, 17],
  ['T', 'HUBBARDHOP', 14, 15],
  ['T', 'HUBBARDHOP', 14, 18],
  ['T', 'HUBBARDHOP', 15, 19],
  ['T', 'HUBBARDHOP', 16, 17],
  ['T', 'HUBBARDHOP', 16, 19],
  ['T', 'HUBBARDHOP', 16, 20],
  ['T', 'HUBBARDHOP', 17, 18],
  ['T', 'HUBBARDHOP', 17, 21],
  ['T', 'HUBBARDHOP', 18, 19],
  ['T', 'HUBBARDHOP', 18, 22],
  ['T', 'HUBBARDHOP', 19, 23],
  ['T', 'HUBBARDHOP', 20, 21],
  ['T', 'HUBBARDHOP', 20, 23],
  ['T', 'HUBBARDHOP', 20, 24],
  ['T', 'HUBBARDHOP', 21, 22],
  ['T', 'HUBBARDHOP', 21, 25],
  ['T', 'HUBBARDHOP', 22, 23],
  ['T', 'HUBBARDHOP', 22, 26],
  ['T', 'HUBBARDHOP', 23, 27],
  ['T', 'HUBBARDHOP', 24, 25],
  ['T', 'HUBBARDHOP', 24, 27],
  ['T', 'HUBBARDHOP', 24, 28],
  ['T', 'HUBBARDHOP', 25, 26],
  ['T', 'HUBBARDHOP', 25, 29],
  ['T', 'HUBBARDHOP', 26, 27],
  ['T', 'HUBBARDHOP', 26, 30],
  ['T', 'HUBBARDHOP', 27, 31],
  ['T', 'HUBBARDHOP', 28, 29],
  ['T', 'HUBBARDHOP', 28, 31],
  ['T', 'HUBBARDHOP', 28, 32],
  ['T', 'HUBBARDHOP', 29, 30],
  ['T', 'HUBBARDHOP', 29, 33],
  ['T', 'HUBBARDHOP', 30, 31],
  ['T', 'HUBBARDHOP', 30, 34],
  ['T', 'HUBBARDHOP', 31, 35],
  ['T', 'HUBBARDHOP', 32, 33],
  ['T', 'HUBBARDHOP', 32, 35],
  ['T', 'HUBBARDHOP', 32, 36],
  ['T', 'HUBBARDHOP', 33, 34],
  ['T', 'HUBBARDHOP', 33, 37],
  ['T', 'HUBBARDHOP', 34, 35],
  ['T', 'HUBBARDHOP', 34, 38],
  ['T', 'HUBBARDHOP', 35, 39],
  ['T', 'HUBBARDHOP', 36, 37],
  ['T', 'HUBBARDHOP', 36, 39],
  ['T', 'HUBBARDHOP', 36, 40],
  ['T', 'HUBBARDHOP', 37, 38],
  ['T', 'HUBBARDHOP', 37, 41],
  ['T', 'HUBBARDHOP', 38, 39],
  ['T', 'HUBBARDHOP', 38, 42],
  ['T', 'HUBBARDHOP', 39, 43],
  ['T', 'HUBBARDHOP', 40, 41],
  ['T', 'HUBBARDHOP', 40, 43],
  ['T', 'HUBBARDHOP', 40, 44],
  ['T', 'HUBBARDHOP', 41, 42],
  ['T', 'HUBBARDHOP', 41, 45],
  ['T', 'HUBBARDHOP', 42, 43],
  ['T', 'HUBBARDHOP', 42, 46],
  ['T', 'HUBBARDHOP', 43, 47],
  ['T', 'HUBBARDHOP', 44, 45],
  ['T', 'HUBBARDHOP', 44, 47],
  ['T', 'HUBBARDHOP', 44, 48],
  ['T', 'HUBBARDHOP', 45, 46],
  ['T', 'HUBBARDHOP', 45, 49],
  ['T', 'HUBBARDHOP', 46, 47],
  ['T', 'HUBBARDHOP', 46, 50],
  ['T', 'HUBBARDHOP', 47, 51],
  ['T', 'HUBBARDHOP', 48, 49],
  ['T', 'HUBBARDHOP', 48, 51],
  ['T', 'HUBBARDHOP', 48, 52],
  ['T', 'HUBBARDHOP', 49, 50],
  ['T', 'HUBBARDHOP', 49, 53],
  ['T', 'HUBBARDHOP', 50, 51],
  ['T', 'HUBBARDHOP', 50, 54],
  ['T', 'HUBBARDHOP', 51, 55],
  ['T', 'HUBBARDHOP', 52, 53],
  ['T', 'HUBBARDHOP', 52, 55],
  ['T', 'HUBBARDHOP', 52, 56],
  ['T', 'HUBBARDHOP', 53, 54],
  ['T', 'HUBBARDHOP', 53, 57],
  ['T', 'HUBBARDHOP', 54, 55],
  ['T', 'HUBBARDHOP', 54, 58],
  ['T', 'HUBBARDHOP', 55, 59],
  ['T', 'HUBBARDHOP', 56, 57],
  ['T', 'HUBBARDHOP', 56, 59],
  ['T', 'HUBBARDHOP', 56, 60],
  ['T', 'HUBBARDHOP', 57, 58],
  ['T', 'HUBBARDHOP', 57, 61],
  ['T', 'HUBBARDHOP', 58, 59],
  ['T', 'HUBBARDHOP', 58, 62],
  ['T', 'HUBBARDHOP', 59, 63],
  ['T', 'HUBBARDHOP', 60, 61],
  ['T', 'HUBBARDHOP', 60, 63],
  ['T', 'HUBBARDHOP', 60, 64],
  ['T', 'HUBBARDHOP', 61, 62],
  ['T', 'HUBBARDHOP', 61, 65],
  ['T', 'HUBBARDHOP', 62, 63],
  ['T', 'HUBBARDHOP', 62, 66],
  ['T', 'HUBBARDHOP', 63, 67],
  ['T', 'HUBBARDHOP', 64, 65],
  ['T', 'HUBBARDHOP', 64, 67],
  ['T', 'HUBBARDHOP', 64, 68],
  ['T', 'HUBBARDHOP', 65, 66],
  ['T', 'HUBBARDHOP', 65, 69],
  ['T', 'HUBBARDHOP', 66, 67],
  ['T', 'HUBBARDHOP', 66, 70],
  ['T', 'HUBBARDHOP', 67, 71],
  ['T', 'HUBBARDHOP', 68, 69],
  ['T', 'HUBBARDHOP', 68, 71],
  ['T', 'HUBBARDHOP', 68, 72],
  ['T', 'HUBBARDHOP', 69, 70],
  ['T', 'HUBBARDHOP', 69, 73],
  ['T', 'HUBBARDHOP', 70, 71],
  ['T', 'HUBBARDHOP', 70, 74],
  ['T', 'HUBBARDHOP', 71, 75],
  ['T', 'HUBBARDHOP', 72, 73],
  ['T', 'HUBBARDHOP', 72, 75],
  ['T', 'HUBBARDHOP', 72, 76],
  ['T', 'HUBBARDHOP', 73, 74],
  ['T', 'HUBBARDHOP', 73, 77],
  ['T', 'HUBBARDHOP', 74, 75],
  ['T', 'HUBBARDHOP', 74, 78],
  ['T', 'HUBBARDHOP', 75, 79],
  ['T', 'HUBBARDHOP', 76, 77],
  ['T', 'HUBBARDHOP', 76, 79],
  ['T', 'HUBBARDHOP', 76, 80],
  ['T', 'HUBBARDHOP', 77, 78],
  ['T', 'HUBBARDHOP', 77, 81],
  ['T', 'HUBBARDHOP', 78, 79],
  ['T', 'HUBBARDHOP', 78, 82],
  ['T', 'HUBBARDHOP', 79, 83],
  ['T', 'HUBBARDHOP', 80, 81],
  ['T', 'HUBBARDHOP', 80, 83],
  ['T', 'HUBBARDHOP', 80, 84],
  ['T', 'HUBBARDHOP', 81, 82],
  ['T', 'HUBBARDHOP', 81, 85],
  ['T', 'HUBBARDHOP', 82, 83],
  ['T', 'HUBBARDHOP', 82, 86],
  ['T', 'HUBBARDHOP', 83, 87],
  ['T', 'HUBBARDHOP', 84, 85],
  ['T', 'HUBBARDHOP', 84, 87],
  ['T', 'HUBBARDHOP', 84, 88],
  ['T', 'HUBBARDHOP', 85, 86],
  ['T', 'HUBBARDHOP', 85, 89],
  ['T', 'HUBBARDHOP', 86, 87],
  ['T', 'HUBBARDHOP', 86, 90],
  ['T', 'HUBBARDHOP', 87, 91],
  ['T', 'HUBBARDHOP', 88, 89],
  ['T', 'HUBBARDHOP', 88, 91],
  ['T', 'HUBBARDHOP', 88, 92],
  ['T', 'HUBBARDHOP', 89, 90],
  ['T', 'HUBBARDHOP', 89, 93],
  ['T', 'HUBBARDHOP', 90, 91],
  ['T', 'HUBBARDHOP', 90, 94],
  ['T', 'HUBBARDHOP', 91, 95],
  ['T', 'HUBBARDHOP', 92, 93],
  ['T', 'HUBBARDHOP', 92, 95],
  ['T', 'HUBBARDHOP', 92, 96],
  ['T', 'HUBBARDHOP', 93, 94],
  ['T', 'HUBBARDHOP', 93, 97],
  ['T', 'HUBBARDHOP', 94, 95],
  ['T', 'HUBBARDHOP', 94, 98],
  ['T', 'HUBBARDHOP', 95, 99],
  ['T', 'HUBBARDHOP', 96, 97],
  ['T', 'HUBBARDHOP', 96, 99],
  ['T', 'HUBBARDHOP', 96, 100],
  ['T', 'HUBBARDHOP', 97, 98],
  ['T', 'HUBBARDHOP', 97, 101],
  ['T', 'HUBBARDHOP', 98, 99],
  ['T', 'HUBBARDHOP', 98, 102],
  ['T', 'HUBBARDHOP', 99, 103],
  ['T', 'HUBBARDHOP', 100, 101],
  ['T', 'HUBBARDHOP', 100, 103],
  ['T', 'HUBBARDHOP', 100, 104],
  ['T', 'HUBBARDHOP', 101, 102],
  ['T', 'HUBBARDHOP', 101, 105],
  ['T', 'HUBBARDHOP', 102, 103],
  ['T', 'HUBBARDHOP', 102, 106],
  ['T', 'HUBBARDHOP', 103, 107],
  ['T', 'HUBBARDHOP', 104, 105],
  ['T', 'HUBBARDHOP', 104, 107],
  ['T', 'HUBBARDHOP', 104, 108],
  ['T', 'HUBBARDHOP', 105, 106],
  ['T', 'HUBBARDHOP', 105, 109],
  ['T', 'HUBBARDHOP', 106, 107],
  ['T', 'HUBBARDHOP', 106, 110],
  ['T', 'HUBBARDHOP', 107, 111],
  ['T', 'HUBBARDHOP', 108, 109],
  ['T', 'HUBBARDHOP', 108, 111],
  ['T', 'HUBBARDHOP', 108, 112],
  ['T', 'HUBBARDHOP', 109, 110],
  ['T', 'HUBBARDHOP', 109, 113],
  ['T', 'HUBBARDHOP', 110, 111],
  ['T', 'HUBBARDHOP', 110, 114],
  ['T', 'HUBBARDHOP', 111, 115],
  ['T', 'HUBBARDHOP', 112, 113],
  ['T', 'HUBBARDHOP', 112, 115],
  ['T', 'HUBBARDHOP', 112, 116],
  ['T', 'HUBBARDHOP', 113, 114],
  ['T', 'HUBBARDHOP', 113, 117],
  ['T', 'HUBBARDHOP', 114, 115],
  ['T', 'HUBBARDHOP', 114, 118],
  ['T', 'HUBBARDHOP', 115, 119],
  ['T', 'HUBBARDHOP', 116, 117],
  ['T', 'HUBBARDHOP', 116, 119],
  ['T', 'HUBBARDHOP', 116, 120],
  ['T', 'HUBBARDHOP', 117, 118],
  ['T', 'HUBBARDHOP', 117, 121],
  ['T', 'HUBBARDHOP', 118, 119],
  ['T', 'HUBBARDHOP', 118, 122],
  ['T', 'HUBBARDHOP', 119, 123],
  ['T', 'HUBBARDHOP', 120, 121],
  ['T', 'HUBBARDHOP', 120, 123],
  ['T', 'HUBBARDHOP', 120, 124],
  ['T', 'HUBBARDHOP', 121, 122],
  ['T', 'HUBBARDHOP', 121, 125],
  ['T', 'HUBBARDHOP', 122, 123],
  ['T', 'HUBBARDHOP', 122, 126],
  ['T', 'HUBBARDHOP', 123, 127],
  ['T', 'HUBBARDHOP', 124, 125],
  ['T', 'HUBBARDHOP', 124, 127],
  ['T', 'HUBBARDHOP', 125, 126],
  ['T', 'HUBBARDHOP', 126, 127],
  ['Tp', 'HUBBARDHOP', 0, 7],
  ['Tp', 'HUBBARDHOP', 1, 4],
  ['Tp', 'HUBBARDHOP', 2, 5],
  ['Tp', 'HUBBARDHOP', 3, 6],
  ['Tp', 'HUBBARDHOP', 4, 11],
  ['Tp', 'HUBBARDHOP', 5, 8],
  ['Tp', 'HUBBARDHOP', 6, 9],
  ['Tp', 'HUBBARDHOP', 7, 10],
  ['Tp', 'HUBBARDHOP', 8, 15],
  ['Tp', 'HUBBARDHOP', 9, 12],
  ['Tp', 'HUBBARDHOP', 10, 13],
  ['Tp', 'HUBBARDHOP', 11, 14],
  ['Tp', 'HUBBARDHOP', 12, 19],
  ['Tp', 'HUBBARDHOP', 13, 16],
  ['Tp', 'HUBBARDHOP', 14, 17],
  ['Tp', 'HUBBARDHOP', 15, 18],
  ['Tp', 'HUBBARDHOP', 16, 23],
  ['Tp', 'HUBBARDHOP', 17, 20],
  ['Tp', 'HUBBARDHOP', 18, 21],
  ['Tp', 'HUBBARDHOP', 19, 22],
  ['Tp', 'HUBBARDHOP', 20, 27],
  ['Tp', 'HUBBARDHOP', 21, 24],
  ['Tp', 'HUBBARDHOP', 22, 25],
  ['Tp', 'HUBBARDHOP', 23, 26],
  ['Tp', 'HUBBARDHOP', 24, 31],
  ['Tp', 'HUBBARDHOP', 25, 28],
  ['Tp', 'HUBBARDHOP', 26, 29],
  ['Tp', 'HUBBARDHOP', 27, 30],
  ['Tp', 'HUBBARDHOP', 28, 35],
  ['Tp', 'HUBBARDHOP', 29, 32],
  ['Tp', 'HUBBARDHOP', 30, 33],
  ['Tp', 'HUBBARDHOP', 31, 34],
  ['Tp', 'HUBBARDHOP', 32, 39],
  ['Tp', 'HUBBARDHOP', 33, 36],
  ['Tp', 'HUBBARDHOP', 34, 37],
  ['Tp', 'HUBBARDHOP', 35, 38],
  ['Tp', 'HUBBARDHOP', 36, 43],
  ['Tp', 'HUBBARDHOP', 37, 40],
  ['Tp', 'HUBBARDHOP', 38, 41],
  ['Tp', 'HUBBARDHOP', 39, 42],
  ['Tp', 'HUBBARDHOP', 40, 47],
  ['Tp', 'HUBBARDHOP', 41, 44],
  ['Tp', 'HUBBARDHOP', 42, 45],
  ['Tp', 'HUBBARDHOP', 43, 46],
  ['Tp', 'HUBBARDHOP', 44, 51],
  ['Tp', 'HUBBARDHOP', 45, 48],
  ['Tp', 'HUBBARDHOP', 46, 49],
  ['Tp', 'HUBBARDHOP', 47, 50],
  ['Tp', 'HUBBARDHOP', 48, 55],
  ['Tp', 'HUBBARDHOP', 49, 52],
  ['Tp', 'HUBBARDHOP', 50, 53],
  ['Tp', 'HUBBARDHOP', 51, 54],
  ['Tp', 'HUBBARDHOP', 52, 59],
  ['Tp', 'HUBBARDHOP', 53, 56],
  ['Tp', 'HUBBARDHOP', 54, 57],
  ['Tp', 'HUBBARDHOP', 55, 58],
  ['Tp', 'HUBBARDHOP', 56, 63],
  ['Tp', 'HUBBARDHOP', 57, 60],
  ['Tp', 'HUBBARDHOP', 58, 61],
  ['Tp', 'HUBBARDHOP', 59, 62],
  ['Tp', 'HUBBARDHOP', 60, 67],
  ['Tp', 'HUBBARDHOP', 61, 64],
  ['Tp', 'HUBBARDHOP', 62, 65],
  ['Tp', 'HUBBARDHOP', 63, 66],
  ['Tp', 'HUBBARDHOP', 64, 71],
  ['Tp', 'HUBBARDHOP', 65, 68],
  ['Tp', 'HUBBARDHOP', 66, 69],
  ['Tp', 'HUBBARDHOP', 67, 70],
  ['Tp', 'HUBBARDHOP', 68, 75],
  ['Tp', 'HUBBARDHOP', 69, 72],
  ['Tp', 'HUBBARDHOP', 70, 73],
  ['Tp', 'HUBBARDHOP', 71, 74],
  ['Tp', 'HUBBARDHOP', 72, 79],
  ['Tp', 'HUBBARDHOP', 73, 76],
  ['Tp', 'HUBBARDHOP', 74, 77],
  ['Tp', 'HUBBARDHOP', 75, 78],
  ['Tp', 'HUBBARDHOP', 76, 83],
  ['Tp', 'HUBBARDHOP', 77, 80],
  ['Tp', 'HUBBARDHOP', 78, 81],
  ['Tp', 'HUBBARDHOP', 79, 82],
  ['Tp', 'HUBBARDHOP', 80, 87],
  ['Tp', 'HUBBARDHOP', 81, 84],
  ['Tp', 'HUBBARDHOP', 82, 85],
  ['Tp', 'HUBBARDHOP', 83, 86],
  ['Tp', 'HUBBARDHOP', 84, 91],
  ['Tp', 'HUBBARDHOP', 85, 88],
  ['Tp', 'HUBBARDHOP', 86, 89],
  ['Tp', 'HUBBARDHOP', 87, 90],
  ['Tp', 'HUBBARDHOP', 88, 95],
  ['Tp', 'HUBBARDHOP', 89, 92],
  ['Tp', 'HUBBARDHOP', 90, 93],
  ['Tp', 'HUBBARDHOP', 91, 94],
  ['Tp', 'HUBBARDHOP', 92, 99],
  ['Tp', 'HUBBARDHOP', 93, 96],
  ['Tp', 'HUBBARDHOP', 94, 97],
  ['Tp', 'HUBBARDHOP', 95, 98],
  ['Tp', 'HUBBARDHOP', 96, 103],
  ['Tp', 'HUBBARDHOP', 97, 100],
  ['Tp', 'HUBBARDHOP', 98, 101],
  ['Tp', 'HUBBARDHOP', 99, 102],
  ['Tp', 'HUBBARDHOP', 100, 107],
  ['Tp', 'HUBBARDHOP', 101, 104],
  ['Tp', 'HUBBARDHOP', 102, 105],
  ['Tp', 'HUBBARDHOP', 103, 106],
  ['Tp', 'HUBBARDHOP', 104, 111],
  ['Tp', 'HUBBARDHOP', 105, 108],
  ['Tp', 'HUBBARDHOP', 106, 109],
  ['Tp', 'HUBBARDHOP', 107, 110],
  ['Tp', 'HUBBARDHOP', 108, 115],
  ['Tp', 'HUBBARDHOP', 109, 112],
  ['Tp', 'HUBBARDHOP', 110, 113],
  ['Tp', 'HUBBARDHOP', 111, 114],
  ['Tp', 'HUBBARDHOP', 112, 119],
  ['Tp', 'HUBBARDHOP', 113, 116],
  ['Tp', 'HUBBARDHOP', 114, 117],
  ['Tp', 'HUBBARDHOP', 115, 118],
  ['Tp', 'HUBBARDHOP', 116, 123],
  ['Tp', 'HUBBARDHOP', 117, 120],
  ['Tp', 'HUBBARDHOP', 118, 121],
  ['Tp', 'HUBBARDHOP', 119, 122],
  ['Tp', 'HUBBARDHOP', 120, 127],
  ['Tp', 'HUBBARDHOP', 121, 124],
  ['Tp', 'HUBBARDHOP', 122, 125],
  ['Tp', 'HUBBARDHOP', 123, 126],
]
